### ISSUE TITLE
C++ Builder installation

### ISSUE THREAD

**Issue by masacate** [landrix/The-new-Drag-and-Drop-Component-Suite-for-Delphi#8]
Hi,
first thanks for this great suit, just one question, do you plant to supply the installation for C++ Builder XE7 in a close future?
thanks

masacate

**Comment by machi01** [comment]
As far as I can see using DragDrop component by Anders Melander in c++ Builder requires some source changes. I use the command line Delphi 32 / 64 bit compilers delivered with c++builder to get the required headers and object files. Once created, simply add the files to your project. The binaries (.obj resp. .o) may also be sampled in a library (.lib / .a), but basically this makes no differences. 

First copy all .pas (no dcu/project/res files) files into a separate source code folder. Here are the neccessary source changes to get the sources compiled with c++builder delivered delphi compilers :

1. the unit names in the uses clause have to be changed like
"Classes" into "System.Classes" or "Controls" into "Vcl.Controls" Same to function calls like "MessageBox(0 ...", this has to be changed to "Windows.MessageBox(0 ...". C++ Builder provided dcu files are named differently from delphi.

2. DragDropPIDL.pas : the way of importing dll functions has to be changed like:

function ILFindLastID(Pidl: PItemIDList): PItemIDList; stdcall;
  external shell32 index 16;

has to be changed into

function ILFindLastID(Pidl: PItemIDList): PItemIDList; stdcall;
  external shell32 name 'ILFindLastID';

the reason here is that I use the Delphi command line compiler delivered with c++builder only for getting the header and .obj files from *.pas sources and the compiler ended up with an error without these changes.

3. according to compiler errors serveral type casts have to be applied like 
pointer( @MAPIAllocateBuffer), instead of @MAPIAllocateBuffer.

The source changes take an hour or two. DragDropDesign.pas should be excluded. The hereby needed units DesignIntf and DesignEditors are not shipped as binaries with c++ builder. Creating these two units is a bit time consuming and not really neccessary, if DragDropDesign.pas is not explicitly needed.  Compiling can be done with this script  (requires gnu win utils to be installed) :

@echo off
rm *.obj 1>nul 2>nul
rm *.hpp 1>nul 2>nul
rm *.dcu 1>nul 2>nul
rem set c=dcc32
set c=dcc64
echo using %c%
rem %c% -JPHNE -L+UDesignIDE -L+BCB -L+VER140 DragDrop.pas
%c% -JPHNE DragDrop.pas 1>err
%c% -JPHNE DragDropComObj.pas 1>>err
%c% -JPHNE DragDropContext.pas 1>>err
rem %c% -JPHNE DragDropDesign.pas 1>>err
%c% -JPHNE DragDropFile.pas 1>>err
%c% -JPHNE DragDropFormats.pas 1>>err
%c% -JPHNE DragDropGraphics.pas 1>>err
%c% -JPHNE DragDropHandler.pas 1>>err
%c% -JPHNE DragDropInternet.pas 1>>err
%c% -JPHNE DragDropPIDL.pas 1>>err
%c% -JPHNE DragDropText.pas 1>>err
%c% -JPHNE DropComboTarget.pas 1>>err
%c% -JPHNE DropHandler.pas 1>>err
%c% -JPHNE DropSource.pas 1>>err
%c% -JPHNE DropTarget.pas 1>>err
cat err
ls -ali *.hpp

The script must be executed from within a c++builder command prompt. After the script was running several .hpp and .obj/.a - files are created, depending on the memory model. These files have to be added to your project. 

Using DragDrop in your own project is very simple. In your project header insert the onDrop handler (following code is an example only and has not been completely tested) :

class Dropcombotarget::TDropComboTarget;

class TForm1 : public TForm
{
__published:
.
.
.

private:
	void __fastcall DropComboTarget1Drop( System::TObject* Sender, System::Classes::TShiftState ShiftState, const System::Types::TPoint &APoint, int &Effect);
.
.
.
public:
	__fastcall TForm1(TComponent* Owner);
	Dropcombotarget::TDropComboTarget *DropComboTarget1;
.
.
.
};


include DragDrop headers in your .cpp file :

#include <vcl.h>
#pragma hdrstop

#define NO_WIN32_LEAN_AND_MEAN        // needed by DragDrop.hpp

#include "DragDrop.hpp"
#include "DragDropComObj.hpp"
#include "DragDropContext.hpp"
#include "DragDropFile.hpp"
#include "DragDropFormats.hpp"
#include "DragDropGraphics.hpp"
#include "DragDropHandler.hpp"
#include "DragDropInternet.hpp"
#include "DragDropPIDL.hpp"
#include "DragDropText.hpp"
#include "DropComboTarget.hpp"
#include "DropHandler.hpp"
#include "DropSource.hpp"
#include "DropTarget.hpp"


add code to onCreate event :

void __fastcall TForm1::FormCreate(TObject *Sender)
{
	DropComboTarget1                 = new TDropComboTarget( this);
	DropComboTarget1->OnDrop 	= &DropComboTarget1Drop;
	DropComboTarget1->Target 	= ListBoxFiles;  // this is a TListBox that serves as drop target
}


// the onDrop event handler
void __fastcall TForm1::DropComboTarget1Drop( System::TObject* Sender, System::Classes::TShiftState ShiftState, const System::Types::TPoint &APoint, int &Effect)
{
	TStream 	*Stream = NULL;
	int 		i;
	String 		Name;
	String 		TempStr;

	// Clear all formats.
	EditURLURL->Text 		= "";
	EditURLTitle->Text 		= "";
	MemoText->Clear();
	ImageBitmap->Picture->Assign( NULL);
	ImageMetaFile->Picture->Assign( NULL);
	ListBoxFiles->Clear();
	ListBoxMaps->Clear();
	ListViewData->Items->Clear();

	// Extract and display dropped data.
	for( int i = 0; i < DropComboTarget1->Data->Count; i++)
	{
		Name = DropComboTarget1->Data->Names->Strings[ i];
		if( ! Name.IsEmpty())
		{
			Name = IntToStr( i) + ".dat";
		}
		Stream = new TFileStream( ExtractFilePath( Application->ExeName) + Name, fmCreate);

		try
		{
			TListItem  *ListItem = ListViewData->Items->Add();
			ListItem->Caption = Name;
			ListItem->SubItems->Add( IntToStr( DropComboTarget1->Data->Streams[ i]->Size));

			// Copy dropped data to stream (in this case a file stream).
			Stream->CopyFrom( DropComboTarget1->Data->Streams[ i], DropComboTarget1->Data->Streams[ i]->Size);
		}
		__finally
		{
			delete Stream;
		}
	}

	// Copy the rest of the dropped formats.
	ListBoxFiles->Items->Assign( 	DropComboTarget1->Files);
	ListBoxMaps->Items->Assign( 	DropComboTarget1->FileMaps);
	EditURLURL->Text 		= DropComboTarget1->URL;
	EditURLTitle->Text 		= DropComboTarget1->Title;
	ImageBitmap->Picture->Assign(	DropComboTarget1->Bitmap);
	ImageMetaFile->Picture->Assign(	DropComboTarget1->MetaFile);
	MemoText->Lines->Text 	= DropComboTarget1->Text;

	if( DropComboTarget1->Files->Count > 0)
	{
		TempStr = DropComboTarget1->Files->Strings[ 0];
	}
}

The above example needs a Tform with two TEdit, two TListBox, one TMemo one TListView and two TImage controls attached.

Hope, this helps.

**Comment by landrix** [comment]
Thanks.

Can you send me the source? You can use the mail provided in my github profile.

**Comment by Hakasuto** [comment]
Hi, the mail address landrix@users.noreply.github.com is invalid, the mail server reports : mailbox unavailable

**Comment by landrix** [comment]
OK. Look at landrix.de for a mail please

Am 21. Februar 2015 12:04:01 MEZ, schrieb Hakasuto <notifications@github.com>:
>Hi, the mail address landrix@users.noreply.github.com is invalid, the
>mail server reports : mailbox unavailable
>
>---
>Reply to this email directly or view it on GitHub:
>https://github.com/landrix/The-new-Drag-and-Drop-Component-Suite-for-Delphi/issues/8#issuecomment-75366936

Mit freundlichen Grüßen
Sven Harazim

E-Mail: sven.harazim@landrix.de
Telefon: +49 351 833 89 16

Landrix Software GmbH & Co. KG
Eigenheimstr. 12
D - 01445 Radebeul
Telefon: +49 351 833 89 16
Fax: +49 351 833 89 04
Internet: https://www.landrix.de
E-Mail: info@landrix.de
Sitz Radebeul, HRA 9366, Amtsgericht Dresden
Steuer-Nr.: 209/158/01626
Persönlich haftende Gesellschafterin:
Landrix Geschäftsführungs-GmbH
Sitz Radebeul, HRB 33993, Amtsgericht Dresden
Geschäftsführer:
Dipl.-Math. Reinhold Harazim
Dipl.-Inf. Sven Harazim

**Comment by masacate** [comment]
Hi,
would the c++ builder compatible sources for your great components suite using the Hakasuto comments? thanks

masacate

**Comment by landrix** [comment]
i working on a patch, i hope on this week it will be done

**Comment by masacate** [comment]
great,
I look forward to hearing from you.
and again thanks very much for your constribuiton to community

masacate
